# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brotato/Univero/wiggachain/Blok-Grandini-praktinis/simplified

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brotato/Univero/wiggachain/Blok-Grandini-praktinis/simplified

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brotato/Univero/wiggachain/Blok-Grandini-praktinis/simplified/CMakeFiles /home/brotato/Univero/wiggachain/Blok-Grandini-praktinis/simplified//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brotato/Univero/wiggachain/Blok-Grandini-praktinis/simplified/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named muh

# Build rule for target.
muh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 muh
.PHONY : muh

# fast build rule for target.
muh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/build
.PHONY : muh/fast

#=============================================================================
# Target rules for targets named muhhash

# Build rule for target.
muhhash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 muhhash
.PHONY : muhhash

# fast build rule for target.
muhhash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhhash.dir/build.make CMakeFiles/muhhash.dir/build
.PHONY : muhhash/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named test_rotate

# Build rule for target.
test_rotate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_rotate
.PHONY : test_rotate

# fast build rule for target.
test_rotate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rotate.dir/build.make CMakeFiles/test_rotate.dir/build
.PHONY : test_rotate/fast

#=============================================================================
# Target rules for targets named experiments

# Build rule for target.
experiments: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 experiments
.PHONY : experiments

# fast build rule for target.
experiments/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/build
.PHONY : experiments/fast

experiments/exp_basic.o: experiments/exp_basic.cpp.o
.PHONY : experiments/exp_basic.o

# target to build an object file
experiments/exp_basic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_basic.cpp.o
.PHONY : experiments/exp_basic.cpp.o

experiments/exp_basic.i: experiments/exp_basic.cpp.i
.PHONY : experiments/exp_basic.i

# target to preprocess a source file
experiments/exp_basic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_basic.cpp.i
.PHONY : experiments/exp_basic.cpp.i

experiments/exp_basic.s: experiments/exp_basic.cpp.s
.PHONY : experiments/exp_basic.s

# target to generate assembly for a file
experiments/exp_basic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_basic.cpp.s
.PHONY : experiments/exp_basic.cpp.s

experiments/exp_guess.o: experiments/exp_guess.cpp.o
.PHONY : experiments/exp_guess.o

# target to build an object file
experiments/exp_guess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_guess.cpp.o
.PHONY : experiments/exp_guess.cpp.o

experiments/exp_guess.i: experiments/exp_guess.cpp.i
.PHONY : experiments/exp_guess.i

# target to preprocess a source file
experiments/exp_guess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_guess.cpp.i
.PHONY : experiments/exp_guess.cpp.i

experiments/exp_guess.s: experiments/exp_guess.cpp.s
.PHONY : experiments/exp_guess.s

# target to generate assembly for a file
experiments/exp_guess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_guess.cpp.s
.PHONY : experiments/exp_guess.cpp.s

experiments/exp_stats.o: experiments/exp_stats.cpp.o
.PHONY : experiments/exp_stats.o

# target to build an object file
experiments/exp_stats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_stats.cpp.o
.PHONY : experiments/exp_stats.cpp.o

experiments/exp_stats.i: experiments/exp_stats.cpp.i
.PHONY : experiments/exp_stats.i

# target to preprocess a source file
experiments/exp_stats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_stats.cpp.i
.PHONY : experiments/exp_stats.cpp.i

experiments/exp_stats.s: experiments/exp_stats.cpp.s
.PHONY : experiments/exp_stats.s

# target to generate assembly for a file
experiments/exp_stats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/exp_stats.cpp.s
.PHONY : experiments/exp_stats.cpp.s

experiments/experiments.o: experiments/experiments.cpp.o
.PHONY : experiments/experiments.o

# target to build an object file
experiments/experiments.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/experiments.cpp.o
.PHONY : experiments/experiments.cpp.o

experiments/experiments.i: experiments/experiments.cpp.i
.PHONY : experiments/experiments.i

# target to preprocess a source file
experiments/experiments.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/experiments.cpp.i
.PHONY : experiments/experiments.cpp.i

experiments/experiments.s: experiments/experiments.cpp.s
.PHONY : experiments/experiments.s

# target to generate assembly for a file
experiments/experiments.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/experiments.dir/build.make CMakeFiles/experiments.dir/experiments/experiments.cpp.s
.PHONY : experiments/experiments.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhhash.dir/build.make CMakeFiles/muhhash.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhhash.dir/build.make CMakeFiles/muhhash.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muhhash.dir/build.make CMakeFiles/muhhash.dir/main.cpp.s
.PHONY : main.cpp.s

muhhash.o: muhhash.cpp.o
.PHONY : muhhash.o

# target to build an object file
muhhash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/muhhash.cpp.o
.PHONY : muhhash.cpp.o

muhhash.i: muhhash.cpp.i
.PHONY : muhhash.i

# target to preprocess a source file
muhhash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/muhhash.cpp.i
.PHONY : muhhash.cpp.i

muhhash.s: muhhash.cpp.s
.PHONY : muhhash.s

# target to generate assembly for a file
muhhash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/muhhash.cpp.s
.PHONY : muhhash.cpp.s

tests/test_golden.o: tests/test_golden.cpp.o
.PHONY : tests/test_golden.o

# target to build an object file
tests/test_golden.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_golden.cpp.o
.PHONY : tests/test_golden.cpp.o

tests/test_golden.i: tests/test_golden.cpp.i
.PHONY : tests/test_golden.i

# target to preprocess a source file
tests/test_golden.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_golden.cpp.i
.PHONY : tests/test_golden.cpp.i

tests/test_golden.s: tests/test_golden.cpp.s
.PHONY : tests/test_golden.s

# target to generate assembly for a file
tests/test_golden.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/test_golden.cpp.s
.PHONY : tests/test_golden.cpp.s

tests/test_rotate.o: tests/test_rotate.cpp.o
.PHONY : tests/test_rotate.o

# target to build an object file
tests/test_rotate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rotate.dir/build.make CMakeFiles/test_rotate.dir/tests/test_rotate.cpp.o
.PHONY : tests/test_rotate.cpp.o

tests/test_rotate.i: tests/test_rotate.cpp.i
.PHONY : tests/test_rotate.i

# target to preprocess a source file
tests/test_rotate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rotate.dir/build.make CMakeFiles/test_rotate.dir/tests/test_rotate.cpp.i
.PHONY : tests/test_rotate.cpp.i

tests/test_rotate.s: tests/test_rotate.cpp.s
.PHONY : tests/test_rotate.s

# target to generate assembly for a file
tests/test_rotate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_rotate.dir/build.make CMakeFiles/test_rotate.dir/tests/test_rotate.cpp.s
.PHONY : tests/test_rotate.cpp.s

versions/algo.o: versions/algo.cpp.o
.PHONY : versions/algo.o

# target to build an object file
versions/algo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/versions/algo.cpp.o
.PHONY : versions/algo.cpp.o

versions/algo.i: versions/algo.cpp.i
.PHONY : versions/algo.i

# target to preprocess a source file
versions/algo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/versions/algo.cpp.i
.PHONY : versions/algo.cpp.i

versions/algo.s: versions/algo.cpp.s
.PHONY : versions/algo.s

# target to generate assembly for a file
versions/algo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/versions/algo.cpp.s
.PHONY : versions/algo.cpp.s

versions/v0_1/muhhash_v0_1.o: versions/v0_1/muhhash_v0_1.cpp.o
.PHONY : versions/v0_1/muhhash_v0_1.o

# target to build an object file
versions/v0_1/muhhash_v0_1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/versions/v0_1/muhhash_v0_1.cpp.o
.PHONY : versions/v0_1/muhhash_v0_1.cpp.o

versions/v0_1/muhhash_v0_1.i: versions/v0_1/muhhash_v0_1.cpp.i
.PHONY : versions/v0_1/muhhash_v0_1.i

# target to preprocess a source file
versions/v0_1/muhhash_v0_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/versions/v0_1/muhhash_v0_1.cpp.i
.PHONY : versions/v0_1/muhhash_v0_1.cpp.i

versions/v0_1/muhhash_v0_1.s: versions/v0_1/muhhash_v0_1.cpp.s
.PHONY : versions/v0_1/muhhash_v0_1.s

# target to generate assembly for a file
versions/v0_1/muhhash_v0_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/muh.dir/build.make CMakeFiles/muh.dir/versions/v0_1/muhhash_v0_1.cpp.s
.PHONY : versions/v0_1/muhhash_v0_1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... experiments"
	@echo "... muh"
	@echo "... muhhash"
	@echo "... test_rotate"
	@echo "... tests"
	@echo "... experiments/exp_basic.o"
	@echo "... experiments/exp_basic.i"
	@echo "... experiments/exp_basic.s"
	@echo "... experiments/exp_guess.o"
	@echo "... experiments/exp_guess.i"
	@echo "... experiments/exp_guess.s"
	@echo "... experiments/exp_stats.o"
	@echo "... experiments/exp_stats.i"
	@echo "... experiments/exp_stats.s"
	@echo "... experiments/experiments.o"
	@echo "... experiments/experiments.i"
	@echo "... experiments/experiments.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... muhhash.o"
	@echo "... muhhash.i"
	@echo "... muhhash.s"
	@echo "... tests/test_golden.o"
	@echo "... tests/test_golden.i"
	@echo "... tests/test_golden.s"
	@echo "... tests/test_rotate.o"
	@echo "... tests/test_rotate.i"
	@echo "... tests/test_rotate.s"
	@echo "... versions/algo.o"
	@echo "... versions/algo.i"
	@echo "... versions/algo.s"
	@echo "... versions/v0_1/muhhash_v0_1.o"
	@echo "... versions/v0_1/muhhash_v0_1.i"
	@echo "... versions/v0_1/muhhash_v0_1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

